config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # NOTE: quirky thing about rails, root resourceS are plural EXCEPT for SESSION. Because
  # security feature is to log a user out if they log in on another client, there is only one
  # session per user and only one resource. So SESSION has a singular RESOURCE.  
  
  # root to: 'controller#action' is the same as root 'controller#action'
  # just wanted to be explicit for "stand alone" pages that don't need 
  # resources per se, though you could do resources and only: [:show]
  root to: 'welcome#home'
  # simple get for the about page 
  get 'welcome/about', to: 'welcome#about'

  resources :contacts
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  email      :string
#  phone      :string
#  title      :string
#  company    :string
#  birth_date :date
#  sex        :string(1)
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

require 'action_view'

class Contact < ApplicationRecord

include ActionView::Helpers::DateHelper 

validates :first_name, presence: true
# validate :birth_date_in_the_past, if: -> { birth_date }

belongs_to :user,
    class_name: 'User',
    foreign_key: :user_id

# def age
#     time_ago_in_words(birth_date)
# end 

# private
# def birth_date_in_the_past
#     if birth_date && birth_date > Time.now 
#         errors[:birth_date] << 'must be in the past'
#     end 
# end 

end 

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :require_user!
    # before_action :require_user!, only: %i(new create edit show update index destroy)

    def index
        contacts = current_user.contacts
        @sorted_contacts = contacts.sort_by{ |contact| contact.last_name.downcase  }
        render :index 
         # NOTE: by doing contacts = current_user.contacts this limits the index view to only the user's contacts
        #  instead ALL contacts by doing @contacts = contacts (all contacts in database)
        # only @sorted_contacts needs to be an instance variable because 
        # only instance variables can be passed to the view, local variables are not.
        # @sorted_contacts are contacts sorted alphabetically by last name, so the 
        # index view will go in alphabetical order, not by the order of when the contact
        # was generated. 
    end 

    def show
        @contact = Contact.find(params[:id])
        render :show 
        # render :show sends over the show TEMPLATE
        # does NOT call show method, or would be an infinite loop
        # calling the show SYMBOL not the method here
    end 

    def create
        @contact = current_user.contacts.new(contact_params)
        if @contact.save
            redirect_to contact_url(@contact) 
        else  
            flash.now[:errors] = @contact.errors.full_messages
            render :new
        end 
    end 

    def new
        # note: this shows the form, does not create a new contact
        # dummy contact object created to capture errors (if any) to display to user
        @contact = Contact.new 
        render :new 
    end 

    def update
        @contact = Contact.find(params[:id])
        # options for an update: update, update!, update_attributes, update_attributes!
        if @contact.update(contact_params)
           redirect_to contact_url(@contact)
        else  
            render :edit 
        end 
    end 

    def edit
        # show an edit form to update an existing contact object
        @contact = Contact.find(params[:id])
        render :edit
    end 

    def destroy
        # delete a contact
        # if we run a method and don't render or redirect, rails will render <name of method>
        @contact = Contact.find(params[:id])
        @contact.destroy
        redirect_to contacts_url 
    end 

    private
    def contact_params
        # either needs to be params[:contact] OR
        # if params are REQUIRED params.require(:contact).permit(). Require is a method, so ()
        # however require will make ALL parameters required
        params[:contact].permit(:first_name, :last_name, :email, :phone, :title, :company, :birth_date, :sex, :notes)
    end 
end 

app/views/contacts/_form.html.erb
<!-- _form is a partial template in erb. Partials always start with an underscore -->

<% action_url = contact.persisted? ? contact_url(contact) : contacts_url %>
<% form_method = contact.persisted? ? "patch" : "post" %>
<% submit_text = contact.persisted? ? "Update Contact" : "Create Contact" %>

<!--  3 variables that are the only difference between create and edit 
action_url, form_method, and submit_text. 
Every model in rails has a persisted method. Persisted checks if element has
been saved to database before. If not saved to database, will save it
-->

<form action="<%= action_url %>" method="post">
<div class="form-group">
    <input type="hidden" name="_method" value="<%= form_method %>">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    <div class="form-row"> 
         <div class="form-group col-sm-5 col-md-5" >
            <label for="contact_first_name" >First Name</label>
            <input type="text" name="contact[first_name]" id="contact_first_name" value="<%= contact.first_name %>" 
            class="form-control">
            <small class="form-text text-muted">First Name is required</small>
        </div>
        <div class="form-group col-sm-5 col-md-5">
            <label for="contact_last_name" >Last Name</label>
            <input type="text" name="contact[last_name]" id="contact_last_name" value="<%= contact.last_name %>" 
            class="form-control">
        </div>
        <div class="form-group col-md-10 col-lg-10" > 
            <label for="contact_email">Email</label>
            <input type="text" name="contact[email]" id="contact_email" value="<%= contact.email %>"
            class="form-control">
            
        </div>
       <div class="form-group col-md-10 col-lg-10">
            <label for="contact_phone">Phone</label>
            <input type="text" name="contact[phone]" id="contact_phone" value="<%= contact.phone %>"
            class="form-control">
        </div>
        <div class="form-group col-md-10 col-lg-10">  
            <label for="contact_title">Title</label>
            <input type="text" name="contact[title]" id="contact_title" value="<%= contact.title %>"
            class="form-control">
        </div>
        <div class="form-group col-md-10 col-lg-6">
            <label for="contact_company">Company</label>
            <input type="text" name="contact[company]" id="contact_company" value="<%= contact.company %>"
            class="form-control">
        </div>
       
        <div class="form-group col-xs-4">  
            <label for="contact_sex">Gender</label>
            <select type="text" name="contact[sex]" id="contact_sex" value="<%= contact.sex %>"
            class="form-control">
                <option value="F"
                    <%= "selected" if @contact.sex == "F" %>>
                    F
                </option>
                <option value="M"
                    <% if @contact.sex == "M" %>
                        selected
                    <% end %>>
                    M
                </option>
                <option value="O" <% if @contact.sex == "O" %>
                        selected <% end %>>
                    O
                </option>
            </select>
        </div>
         <div class="form-group col-md-3 col-lg-3">
            <label for="contact_birth_date">Birth Date</label>
            <input type="text" name="contact[birth_date]" id="contact_birth_date" value="<%= contact.birth_date %>"
            class="form-control">
        </div>
        <div class="form-group col-sm-8 col-md-11 col-lg-9">  
            <label for="contact_notes">Notes</label>
            <textarea name="contact[notes]" id="contact_notes" rows="7" cols="40" class="form-control"><%= contact.notes %></textarea>
        </div>
     </div>
     <div class="text-center">
    <input type="submit" class="btn btn-success" value="<%= submit_text %>" >
    </div>
</form>

app/views/contacts/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-2"> </div>
        <div class="col-md-8 text-center">
          <h1 >Edit Contact</h1>
            <div class="justify-content-center">
              <h2 class="text-center"><%= @contact.first_name %><%=' '%><%= @contact.last_name %></h2>
              <%= render "form", contact: @contact %>
              <br>
              
            </div>
            <a href="<%= contacts_url%>" class="btn btn-primary">Back to Contacts</a>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

app/views/contacts/index.html.erb
<div class="container text-center">
    <div class="row justify-content-center" >
        <div class="col border"></div>
        <div class="col">
            <h1>All Contacts</h1>
            <div class="row">
                <div class="col">
                    <form action="<%= new_contact_url %>" method="get" class=" inline m-2 p-2">
                            <input type="submit" value="New Contact" class="btn btn-primary">
                    </form>
                </div>
            
           </div>
            <ul class="my_uls">
                <% @sorted_contacts.each do |contact| %>
                <li class="card" style="width: 37rem;" >
                     <div class="card-body"> 
                     <h3>
                        <a href ="/contacts/<%= contact.id %>" class="card-title" ><%= contact.first_name %><%=" "%><%= contact.last_name %></a>
                    </h3>    
                        <div class="card-body"> 
                            
                            <a href="<%= edit_contact_url(contact.id) %>" class="btn btn-warning inline" >Edit Contact</a> 
                                <form action="<%= contact_url(contact) %>" method="post" class="m-2 p-2" >
                                    <input
                                        type="hidden"
                                        name="authenticity_token"
                                        value="<%= form_authenticity_token %>">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Delete Contact" class="btn btn-danger ">
                                </form>
                            
                        </div>
                    </div>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col border"></div>
    </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1>Create a New Contact</h1>
            </div>
            <%= render 'shared/errors' %>
            <%= render "form", contact: @contact %>
        </div>
        <div class="col text-center">
        <form action="<%= contacts_url %>" method="get">
            <input type="submit" value="Back to Contacts" class="btn btn-primary"> 
        </form>
        </div>
    </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
    <div class="row justify-content-center">
            <div class="col-lg-4 border">
                    <div class="card " style="width: 30rem;">
                        <div class="m-4">
                            <%= image_tag("man-user.svg", style: "height: 20rem; width: 20rem;", class: "center-item" ) %>
                        </div>
                        <div class="card-body"> 
                            <h3 class="card-title"><%= @contact.first_name  %><%=" " %><%= @contact.last_name %> </h3>
                            <ul class="inline list-group list-group-flush">
                                <li class="list-group-item"><strong>Email: </strong><%= @contact.email %></li>
                                <li class="list-group-item"><strong>Phone: </strong><%= @contact.phone %></li>
                                <li class="list-group-item"><strong>Company: </strong><%= @contact.company %></li>
                                <li class="list-group-item"><strong>Birth Date: </strong><%= @contact.birth_date %></li>
                                <li class="list-group-item"><strong>Gender: </strong><%= @contact.sex %></li>
                                <li class="list-group-item"><strong>Notes: </strong><%= @contact.notes %></li>
                            </ul>
                            <a href="<%= edit_contact_url(@contact) %>" class="btn btn-primary p-2 m-2">Edit <%= @contact.first_name %></a>
                            <a href="<%= contacts_url%>" class="btn btn-success p-2 m-2">Back to Contacts</a>
                            
                        </div>
                        
                    </div>
            </div>
    </div>
</div>