config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # NOTE: quirky thing about rails, root resourceS are plural EXCEPT for SESSION. Because
  # security feature is to log a user out if they log in on another client, there is only one
  # session per user and only one resource. So SESSION has a singular RESOURCE.  
  
  # root to: 'controller#action' is the same as root 'controller#action'
  # just wanted to be explicit for "stand alone" pages that don't need 
  # resources per se, though you could do resources and only: [:show]
  root to: 'welcome#home'
  # simple get for the about page 
  get 'welcome/about', to: 'welcome#about'

  resources :contacts
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light"  >
  <%= link_to "Contacts Manager", root_url, class: "navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
     <li><span class="nav-link"> <%= link_to "Contacts", contacts_url %></span></li>
      <li class="nav-item">
         <li><span class="nav-link">  <%= link_to "About", welcome_about_url %></span></li>
      </li>
          <% if current_user.nil? %>
              <li class="nav-item">
                <li><span class="nav-link"><a href="<%= new_session_url %>">Sign In</a></span></li>
                <li><span class="nav-link"><a href="<%= new_user_url %>">Sign Up</a></li></span>
          <% else %>
                  <li><span class="nav-link"> Hello, <%= current_user.username %></span></li>
              </li>
                <li class="nav-item">
                  <span >
                    <form action="<%= session_url %>" method="post"  > 
                                    <input
                                    type="hidden"
                                    name="authenticity_token"
                                    value="<%= form_authenticity_token %>">
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="submit" value="Logout" style="cursor:pointer; border:none; color: #007bff; background-color:#f8f9fa;" class="nav-link" >        
                    </form>
                  </span>
                </li>
            <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    
      <%= yield %>
    
  </body>
</html>